services:
  frontend:
    build:
      context: .
      dockerfile: Streamlit_Frontend/Dockerfile
    image: visheshrathi2023/sts-frontend:latest
    ports:
      - 8501:8501
    networks:
      - project_network
    depends_on:
      - backend
    volumes:
      - ./Streamlit_Frontend:/app/backend


  backend:
    build:
      context: .
      dockerfile: FastAPI_Backend/Dockerfile
    image: visheshrathi2023/sts-backend:latest
    ports:
      - 8080:8080
    networks:
      - project_network

networks:
  project_network: